CREATE TABLE ACCOUNTS (
    ID        NUMBER PRIMARY KEY,
    NAME      VARCHAR2(100) NOT NULL,
    USERNAME  VARCHAR2(50)  NOT NULL UNIQUE,
    PASSWORD  VARCHAR2(100) NOT NULL,
    PHONE     VARCHAR2(11)  NOT NULL UNIQUE,
    EMAIL     VARCHAR2(100) NOT NULL UNIQUE,
    AGE       NUMBER        NOT NULL,
    BALANCE   NUMBER(10,2)  DEFAULT 0,
    IS_ADMIN  NUMBER(1)     DEFAULT 0,
    IS_ACTIVE NUMBER(1)     DEFAULT 1
);

CREATE SEQUENCE ACCOUNTS_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE TRANSACTIONS (
    ID            NUMBER PRIMARY KEY,
    ACCOUNT_ID    NUMBER        NOT NULL,
    TYPE          VARCHAR2(20)  NOT NULL,
    AMOUNT        NUMBER(10,2)  NOT NULL,
    BALANCE_AFTER NUMBER(10,2)  NOT NULL,
    DETAILS       VARCHAR2(200),
    CONSTRAINT FK_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS(ID) ON DELETE CASCADE
);

CREATE SEQUENCE TRANSACTIONS_SEQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER ACCOUNTS_TRG
BEFORE INSERT ON ACCOUNTS
FOR EACH ROW
BEGIN
    SELECT ACCOUNTS_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

CREATE OR REPLACE TRIGGER TRANSACTIONS_TRG
BEFORE INSERT ON TRANSACTIONS
FOR EACH ROW
BEGIN
    SELECT TRANSACTIONS_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

INSERT INTO ACCOUNTS (NAME, USERNAME, PASSWORD, PHONE, EMAIL, AGE, BALANCE, IS_ADMIN, IS_ACTIVE)
VALUES ('Mahmoud Sliman', 'mahmoud_24', 'Mahmoud#@080', '01026167100', 'mahmoud080@gmail.com', 22, 0, 1, 1);

COMMIT;